name: Code checks
on: 
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/*'
  pull_request:
    branches: [ master ]

jobs:
  test_windows:
    runs-on: windows-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3 # copy repo
      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: 'Run PEP8'
        uses: quentinguidee/pep8-action@v1
        with:
          arguments: '--max-line-length=120'
  test_linux:
    runs-on: ubuntu-latest
    needs: test_windows
    steps:
      - uses: actions/checkout@v3 # copy repo
      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: 'Run PEP8'
        uses: quentinguidee/pep8-action@v1
        with:
          arguments: '--max-line-length=120'
